FROM eclipse-temurin:21-jdk-alpine AS builder

WORKDIR /app

RUN apk add --no-cache maven

COPY ./pom.xml ./

RUN mvn dependency:go-offline -B

COPY ./src ./src

RUN mvn clean package -DskipTests -B

FROM eclipse-temurin:21-jre-alpine AS runtime

WORKDIR /app

COPY --from=builder /app/target/create-service-*.jar app.jar

CMD ["java", "-jar", "app.jar"]